// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucxjzqncduvidjeuxeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y3hqenFuY2R1dmlkamV1eGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTIxMTUsImV4cCI6MjA2MjM2ODExNX0.c4h8vs1Pget9QqGUzZRYCsPZ-tS6Ysq3cCv0PqUkblg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);